[package]
name = "rust_glium_opengl_demo"
version = "0.1.0"
authors = ["Stan Kondrat <stan.kondrat@gmail.com>"]
repository = "https://github.com/stan-kondrat/rust-glium-opengl-demo.git"

[dependencies]
glium = "*"
glium_text = "*"
time = "*"
rand = "*"
